CREATE TABLE USERS 
(
  USER_ID NUMBER NOT NULL 
, USER_NAME VARCHAR2(40) NOT NULL 
, PASSWORD VARCHAR2(30) NOT NULL 
, FIRST_NAME VARCHAR2(20) 
, LAST_NAME VARCHAR2(20) 
, PERSON_DESCRIPTION VARCHAR2(120) 
, PERSON_RATING NUMBER NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);

CREATE TABLE COURSES 
(
  COURSE_ID NUMBER NOT NULL 
, COURSE_NAME VARCHAR2(120) NOT NULL 
, USER_ID NUMBER NOT NULL 
, C_DESCRIPTION VARCHAR2(200) 
, CONSTRAINT COURSES_PK PRIMARY KEY 
  (
    COURSE_ID 
  )
  ENABLE 
);

CREATE TABLE LESSONS 
(
  LESSON_ID NUMBER NOT NULL 
, LESSON_NAME VARCHAR2(50) NOT NULL 
, COURSE_ID VARCHAR2(20) NOT NULL 
, PRICE NUMBER 
, DATE_COURSE DATE 
, CONSTRAINT LESSONS_PK PRIMARY KEY 
  (
    LESSON_ID 
  )
  ENABLE 
);

CREATE TABLE TRANSACTION 
(
  TRANSACTION_ID NUMBER NOT NULL 
, LESSON_ID NUMBER NOT NULL 
, STUDENT_ID NUMBER NOT NULL 
, CONSTRAINT TRANSACTION_PK PRIMARY KEY 
  (
    TRANSACTION_ID 
  , STUDENT_ID 
  )
  ENABLE 
);



